comments/urls.py
from django.urls import path

from .views import comment_create_view, comment_delete_view


app_name = 'comments'
urlpatterns = [
    path('create/', comment_create_view, name='create'),
    path('<int:pk>/delete/', comment_delete_view, name='delete'),
]

pages/urls.py
from django.urls import path

from .views import HomeView, AboutView

app_name = 'pages'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
]

comments/models.py
from django.db import models
from django.conf import settings


RATING_CHOICES = (
    (5, 5),
    (4, 4),
    (3, 3),
    (2, 2),
    (1, 1),
)

class Comment(models.Model):
    leader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comment_to')
    member = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comment_by')
    body = models.TextField()
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)

    def __str__(self):
        return "from " + self.member.username + " to " + self.leader.username

    def get_star_checked(self):
        return "x" * self.rating

    def get_star_unchecked(self):
        return "x" * (5 - self.rating)

comments/forms.py
from django import forms

from .models import Comment

RATING_CHOICES = (
    ('', '별점 주기'),
    (5, 5),
    (4, 4),
    (3, 3),
    (2, 2),
    (1, 1),
)

class CommentForm(forms.ModelForm):
    """Form definition for Comment."""
    body = forms.CharField(label=False, widget=forms.Textarea(attrs={
        "placeholder": "리더님에 대한 리뷰를 달아주세요!",
    }))

    rating = forms.ChoiceField(label=False, choices=RATING_CHOICES)

    class Meta:
        model = Comment
        fields = (
            'body',
            'rating'
        )

    # def clean_body(self):
    #     body = self.cleaned_data['body']
    #     if len(body) > 200:
    #         raise forms.ValidationError("Too long")
    #     return body

comments/views.py
from django.shortcuts import redirect, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.views.generic import DeleteView

from .models import Comment
from .forms import CommentForm

User = get_user_model()


def comment_create_view(request):
    if request.method == 'POST':
        next = request.POST.get('next', '/')
        # Only members can write review
        if not request.user.is_member:
            messages.warning(request, "리뷰는 멤버만 작성할 수 있습니다.")
            return HttpResponseRedirect(next)

        leader_id = request.POST.get('leader_id')
        leader_obj = get_object_or_404(User, id=leader_id)

        # Only one comment per leader is allowed
        if Comment.objects.filter(member=request.user, leader=leader_obj).exists():
            messages.warning(request, "이미 작성한 리뷰가 있습니다.")
            return HttpResponseRedirect(next)
        
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.member = request.user
            form.instance.leader = get_object_or_404(User, id=leader_id)
            form.save()
        else:
            print(form.errors)
            
        return HttpResponseRedirect(next)
    raise Http404


def comment_delete_view(request, pk):
    if request.method == 'POST':
        previous_page = request.POST.get('group_url', '/')
        comment = get_object_or_404(Comment, pk=pk, member=request.user)
        comment.delete()
        return redirect(previous_page)
    raise Http404
    

    

comments/templates/comments/_comment.html
<div class="media comment mb-3">
  <img src={{ comment.member.profile.photo.url }} class="comment__img mr-3 py-1" alt="...">
  <div class="media-body comment__body">
    <h5 class="my-0">{{ comment.member.username }}</h5>
    {% for i in checked %}
      <span class="fas fa-star fa-sm"></span>
    {% endfor %}
    {% for i in unchecked %}
      <span class="far fa-star fa-sm"></span>  
    {% endfor %}
    <p class="mb-2">{{ comment.body|truncatechars:500|linebreaks }}</p>
    
    {% if request.user == comment.member %}
      <form method="POST" action="{% url 'comments:delete' pk=comment.pk %}">{% csrf_token %}
        <input type="hidden" name="group_url" value="{{ group.get_absolute_url }}">
        <button class="comment__button--delete"  type="submit"><i class="far fa-lg fa-trash-alt"></i></button>
      </form>
    {% endif %}
  </div>
</div>

comments/templates/comments/_form.html
<form action="#" method="POST">{% csrf_token %}
  <div class="form-group">
    <textarea class="form-control" name="" id="" cols="30" rows="10"></textarea>
    <button>확인</button>
  </div>
</form>