accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    LeaderGroupListView, 
    MemberGroupListView,
    LeaderSignupView,
    MemberSignupView,
    SignupView,
    CustomLoginView,
    ProfileView,
    ProfileUpdateView,
)

app_name = 'accounts'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('signup/leader/', LeaderSignupView.as_view(), name='leader_signup'),
    path('signup/member', MemberSignupView.as_view(), name='member_signup'),
    path('my_group/leader/', LeaderGroupListView.as_view(), name='leader_group'),
    path('my_group/member/', MemberGroupListView.as_view(), name='member_group'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
]

groups/urls.py
from django.urls import path

from .views import (
    GroupListView,
    GroupDetailView,
    GroupCreateView,
    GroupUpdateView,
    GroupDeleteView,
    group_join_view,
    group_leave_view,
    # email_view
)

app_name = 'groups'
urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('<int:pk>/', GroupDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', GroupUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', GroupDeleteView.as_view(), name='delete'),
    path('<int:pk>/join/', group_join_view, name='join'),
    path('<int:pk>/leave/', group_leave_view, name='leave'),
    path('create/', GroupCreateView.as_view(), name='create'),
    # path('email/', email_view, name='email'),
]

pages/urls.py
from django.urls import path

from .views import HomeView, AboutView

app_name = 'pages'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
]

search/urls.py
from django.urls import path

from .views import (
    SearchGroupView,
)

app_name = 'search'
urlpatterns = [
    path('', SearchGroupView.as_view(), name='query'),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.views.generic import ListView

from groups.models import Group


class SearchGroupView(ListView):
    model = Group
    template_name = 'groups/group_list.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-id')

        # Group name
        if 'group' in self.request.GET:
            group = self.request.GET.get('group')
            if group:
                queryset = queryset.filter(
                    name__icontains=group)

        # Level
        if 'level' in self.request.GET:
            level = self.request.GET.get('level')
            if level:
                queryset = queryset.filter(
                    level__iexact=level)

        # Start date
        if 'start_date' in self.request.GET:
            start_date = self.request.GET.get('start_date')
            if start_date:
                queryset = queryset.filter(
                    start_date__gte=start_date)

        # teacher
        if 'teacher' in self.request.GET:
            teacher = self.request.GET.get('teacher')
            if teacher:
                queryset = queryset.filter(
                    leader__name__icontains=teacher)

        # Location
        if 'location' in self.request.GET:
            location = self.request.GET.get('location')
            if location:
                queryset = queryset.filter(
                    location__icontains=location)

        # Day
        if 'day' in self.request.GET:
            day = self.request.GET.get('day')
            if day:
                queryset = queryset.filter(
                    day__icontains=day)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get query from request
        q_group = self.request.GET.get('group')
        q_level = self.request.GET.get('level')
        q_start_date = self.request.GET.get('start_date')
        q_teacher = self.request.GET.get('teacher')
        q_location = self.request.GET.get('location')
        q_day = self.request.GET.get('day')
        queries = q_group + q_level + q_start_date + q_teacher + q_location + q_day

        if queries != '':
            context['queries'] = [
                q_group,
                q_level,
                q_start_date,
                q_teacher,
                q_location,
                q_day
            ]
        return context
        

templates/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center p-0 m-0" role="alert">
        <!-- <button type="button" class="close m-0 py-1" data-dismiss="alert"><span aria-hidden="true">&times;</span></button> -->
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error          
          {% comment %}
            {% else %}
            {{ message.tags|title }}
          {% endcomment %}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/partials/_breadcrumb.html
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:home' %}">
            <i class="fas fa-home text-secondary"></i> 홈</a>
        </li>
        <li class="breadcrumb-item active">{{ current }}</li>
      </ol>
    </nav>
  </div>
</section>

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
  <section class="footer-content">
    Copyright &copy;
    <span class="year">{% now "Y" %}</span> LearnEng
  </section>
</footer>

templates/partials/_navbar.html
{% load static %}
<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pages:home' %}">
      <i class="fas fa-school"></i>
      <img src="{% static 'img/logo.png' %}" class="logo" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <!-- LINKS ON THE LEFT -->
      <ul class="navbar-nav">
        <li
          {% if 'about' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'pages:about' %}">About</a>
        </li>
        <li
          {% if '/groups/' == request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'groups:list' %}">스터디 찾기</a>
        </li>
        {% if request.user.is_leader == True %}
        <li
          {% if 'create' in request.path %}
          class="nav-item active mr-3"
          {% else %}
          class="nav-item mr-3"
          {% endif %}
        >        
          <a class="nav-link" href="{% url 'groups:create' %}">내 스터디 만들기 <i class="fas fa-plus"></i></a>
        </li>          
        {% endif %}
      </ul>

      <!-- LINKS ON THE RIGHT -->
      <ul class="navbar-nav ml-auto">
        <!-- FOR AUTHENTICATED USERS -->
        {% if user.is_authenticated %}
          <li 
            {% if 'my_group' in request.path or 'profile' in request.path %}
            class="nav-item dropdown active"
            {% else %}
            class="nav-item dropdown"
            {% endif %}
          >
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_leader %}
              <a class="dropdown-item" href="{% url 'accounts:leader_group' %}">내 스터디</a>
              {% elif user.is_member %}
              <a class="dropdown-item" href="{% url 'accounts:member_group' %}">내 스터디</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'accounts:profile' %}">프로필</a>
            </div>
          </li>
          <li class="nav-item mr-3">
            <a href="{% url 'accounts:logout' %}" class="nav-link">
              <i class="fas fa-sign-out-alt"></i> 로그아웃
            </a>
          </li>
        {% else %}
          <!-- FOR UNAUTH USERS -->
          <li
            {% if 'signup' in request.path %}
            class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:signup' %}">
              <i class="fas fa-user-plus"></i> 회원가입</a>
          </li>
          <li
            {% if 'login' in request.path %}
            class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'accounts:login' %}">
              <i class="fas fa-sign-in-alt"></i>
              로그인</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/partials/_paginator.html
<div class="row">
  <div class="col-md-12" style="display: flex; justify-content: center;">
    {% if page_obj.has_other_pages %}
    <div>
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">&laquo;</a>
      </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active">
        <a class="page-link">{{ i }}</a>
      </li>
      {% else %}
      <li class="page-item">
        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
      </li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">&raquo;</a>
      </li>
      {% endif %}
    </ul>
    </div>
    </div>
    {% endif %}
</div>

templates/partials/_search_form.html
<div class="search">
  <form action="{% url 'search:query' %}">
    <!-- Form Row 1 -->
    <div class="form-row">
      <div class="col-md-4 mb-3">
        <label class="sr-only">Group</label>
        <input type="text" name="group" class="form-control" placeholder="스터디 이름">
      </div>

      <div class="col-md-4 mb-3">
        <label class="sr-only">Location</label>
        <input type="text" name="location" class="form-control" placeholder="지역">
      </div>

      <div class="col-md-4 mb-3">
        <label class="sr-only">Level</label>
        <select name="level" class="form-control">
          <option value="" selected="true">-레벨-</option>
          <option value="초급">초급</option>
          <option value="중급">중급</option>
          <option value="고급">고급</option>
        </select>
      </div>
    </div>
    <!-- Form Row 2 -->
    <div class="form-row">
      <div class="col-md-4 mb-3">
        <label class="sr-only">Teacher</label>
        <input type="text" name="teacher" class="form-control" placeholder="리더 이름">
      </div>

      <div class="col-md-4 mb-3">
        <label class="sr-only">Start Date</label>
        <input type="text" name="start_date" class="form-control" placeholder="시작일">
      </div>

      <div class="col-md-4 mb-3">
        <label class="sr-only">Day</label>
        <select name="day" class="form-control">
          <option value="" selected="true">-요일-</option>
          <option value="월요일">월요일</option>
          <option value="화요일">화요일</option>
          <option value="수요일">수요일</option>
          <option value="목요일">목요일</option>
          <option value="금요일">금요일</option>
          <option value="토요일">토요일</option>
          <option value="일요일">일요일</option>
        </select>
      </div>
    </div>
    <button class="btn btn-secondary btn-block mt-4" type="submit">검색하기</button>
  </form>
</div>




{% comment %}
  <!-- <section class="multi-search-section">
  <div class="msf-warp">
    <div class="container">
      <h5>스터디그룹 검색하기</h5>
      <form class="multi-search-form" action="{% url 'search:query' %}">
        <input type="text" name="group" placeholder="Group">
        <!-- <input type="text" name="level" placeholder="Level"> -->
        <select name="level">
          <option selected="true" disabled>레벨</option>
          <option value="초급">초급</option>
          <option value="중급">중급</option>
          <option value="고급">고급</option>
        </select>
        <input type="date" name="date">
        <input type="text" name="teacher" placeholder="Teacher">
        <input type="text" name="location" placeholder="Location">
        <button class="site-btn">검색 <i class="fa fa-angle-right"></i></button>
      </form>
    </div>
  </div>
</section> -->
{% endcomment %}
  

templates/partials/_topbar.html
<!-- Top Bar -->
<section class="top-bar">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <!-- <i class="fas fa-phone"></i> (617)-555-5555 -->
      </div>
      <div class="col-md-4 text-center">
        <i class="fas fa-envelope-open"></i>
        <a href="mailto:contact@learn-eng.net">contact@learn-eng.net</a>
      </div>
      <div class="col-md-4">
        <!-- Alerts -->
        {% include 'partials/_alerts.html' %}
        <!-- <div class="social text-right">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="#">
            <i class="fab fa-facebook"></i>
          </a>
          <a href="#">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="#">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#">
            <i class="fab fa-pinterest"></i>
          </a>
        </div> -->
      </div>
    </div>
  </div>
</section>