comments/urls.py
from django.urls import path

from .views import comment_create_view, comment_delete_view


app_name = 'comments'
urlpatterns = [
    path('create/', comment_create_view, name='create'),
    path('<int:pk>/delete/', comment_delete_view, name='delete'),
]

groups/urls.py
from django.urls import path

from .views import (
    GroupListView,
    GroupDetailView,
    GroupCreateView,
    GroupUpdateView,
    GroupDeleteView,
    group_join_view,
    group_leave_view,
    # email_view
)

app_name = 'groups'
urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('<int:pk>/', GroupDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', GroupUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', GroupDeleteView.as_view(), name='delete'),
    path('<int:pk>/join/', group_join_view, name='join'),
    path('<int:pk>/leave/', group_leave_view, name='leave'),
    path('create/', GroupCreateView.as_view(), name='create'),
    # path('email/', email_view, name='email'),
]

pages/urls.py
from django.urls import path

from .views import HomeView, AboutView

app_name = 'pages'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
]

groups/models.py
from datetime import date
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models.signals import pre_save, m2m_changed
from django.conf import settings
from django.urls import reverse


LEVEL_CHOICES = (
    ('초급', '초급'),
    ('중급', '중급'),
    ('고급', '고급')
)

DAY_CHOICES = (
    ('월요일', '월요일'),
    ('화요일', '화요일'),
    ('수요일', '수요일'),
    ('목요일', '목요일'),
    ('금요일', '금요일'),
    ('토요일', '토요일'),
    ('일요일', '일요일')
)

STATUS_CHOICES = (
    ('open', 'Open'),
    ('closed', 'Closed'),
    ('full', 'Full')
)


class Group(models.Model):
    leader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='leader_of')
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='member_of')
    name = models.CharField('스터디명', max_length=140)
    photo = models.ImageField('메인 이미지', upload_to='groups/%Y/%m/%d/',
                              default='default/group-default.jpg')
    level = models.CharField('레벨', max_length=30, choices=LEVEL_CHOICES, default='elementary')
    start_date = models.DateField('시작일')
    day = models.CharField('요일', max_length=30, default='토요일', choices=DAY_CHOICES)
    time = models.CharField('시간', max_length=30)
    duration = models.PositiveSmallIntegerField('기간(주)', default=4)
    price = models.PositiveSmallIntegerField('참여비(만원)', default=0)
    size = models.PositiveSmallIntegerField('최대정원', default=4, validators=[MaxValueValidator(8), MinValueValidator(1)])
    location = models.CharField('지역', max_length=30)
    description = models.TextField('스터디 소개')
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=40, default='open', choices=STATUS_CHOICES)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'pk': self.pk})


# class GroupMember(models.Model):
#     group = models.ForeignKey(Group, on_delete=models.CASCADE)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


# Use signals to alter Group.status
def members_changed(sender, instance, action, **kwargs):
    if instance.members.count() >= instance.size:
        instance.status = 'full'
        instance.save()
    else:
        instance.status = 'open'
        instance.save()

m2m_changed.connect(members_changed, sender=Group.members.through)

# def pre_save_alter_status(sender, instance, **kwargs):
#     if instance.start_date < date.today():
#         instance.status = 'closed'
#     # else:
#         # # if instance.members.count() < instance.size:
#         # instance.status = 'open'
#         # print('in fact?')

# pre_save.connect(pre_save_alter_status, sender=Group)

# Status 로직
# 시작 날짜가 지나면 다른 상관 없이 closed
# 시작 날짜가 안 지났으면 인원으로 open or full

groups/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget
from django.utils import timezone

from .models import Group


class GroupForm(forms.ModelForm):
    """Form definition for Group."""
    start_date = forms.CharField(
        widget=forms.TextInput(attrs={'id': 'datepicker'}),
        label='시작일'
    )
    photo = forms.ImageField(label='메인 이미지(Optional)', required=False)
    size = forms.IntegerField(label='정원(최대 8명)')

    time = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'예) 17:00 ~ 19:00'}),
        label='시간'
    )

    location = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder':'예) 홍대'}),
        label='지역'
    )

    class Meta:
        model = Group
        fields = (
            'name', 'photo', 'level', 'start_date', 'day',
            'time', 'duration', 'price', 'size', 'location',
            'description'
        )


# class ContactForm(forms.Form):
#     from_email = forms.EmailField(required=True)
#     subject = forms.CharField(required=True)
#     message = forms.CharField(widget=forms.Textarea)

groups/views.py
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from .forms import GroupForm
from .models import Group
from comments.models import Comment
from comments.forms import CommentForm


class GroupListView(ListView):
    model = Group
    template_name = 'groups/group_list.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-id') #.filter(start_date__gte=datetime.now()) Change this before production
        return queryset


class GroupDetailView(LoginRequiredMixin, DetailView):
    model = Group
    template_name = 'groups/group_detail.html'

    def get_context_data(self, **kwargs):
        obj = self.get_object()
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(leader=obj.leader).order_by('-pk')
        context['form'] = CommentForm()
        return context
    

class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    template_name = 'groups/group_create.html'
    form_class = GroupForm

    def get(self, request, *args, **kwargs):
        self.object = None
        # Check if the user is teacher
        if request.user.is_leader == False:
            messages.warning(request, "스터디 개설은 리더만 가능합니다.")
            return redirect('pages:home')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        group = form.save(commit=False)  # creates a group instance by using the input of the form
        group.leader = self.request.user
        group.save()
        messages.success(self.request, "새 그룹 생성이 완료되었습니다.")        
        return redirect(group.get_absolute_url())


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    template_name = 'groups/group_update.html'
    form_class = GroupForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Check if current user is the owner of this instance
        if self.object.leader != request.user:
            messages.warning(request, "해당 스터디에 대한 권한이 없습니다.")
            return redirect('pages:home')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "기존 그룹이 업데이트 되었습니다.")
        return redirect('groups:detail', pk=self.object.id)


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = 'groups/group_delete.html'
    success_url = reverse_lazy('groups:list')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.leader != request.user:
            messages.warning(request, "해당 스터디에 대한 권한이 없습니다.")
            return redirect('pages:home')
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


@login_required
def group_join_view(request, **kwargs):
    pk_ = kwargs['pk'] # This is from the url, or request.path
    group = get_object_or_404(Group, pk=pk_)
    user = get_user(request)

    if user in group.members.all():
        messages.warning(request, '이미 해당 그룹의 멤버입니다.')
        return redirect(group.get_absolute_url())

    if group.members.count() >= group.size:
        messages.warning(request, '해당 그룹은 정원이 초과되었습니다.')
        return redirect('pages:home')

    if request.method == "POST":
        contact_ = request.POST.get('contact')
        group.members.add(user)
        # group.save() m2m field는 따로 save() 필요없음 그래서, signal 쓸때 m2m_changed 써야함
        user.contact = contact_
        user.save()
        messages.success(request, "그룹 참여가 완료되었습니다.")
        return redirect(group.get_absolute_url())
    
    context = {
        'group': group
    }
    return render(request, 'groups/group_join.html', context)


@login_required
def group_leave_view(request, **kwargs):
    pk_ = kwargs['pk']
    group = get_object_or_404(Group, pk=pk_)
    user = get_user(request)

    if user not in group.members.all():
        messages.warning(request, "해당 그룹의 멤버가 아닙니다.")
        return redirect(group.get_absolute_url())

    if request.method == "POST":
        group.members.remove(user)
        messages.success(request, '그룹 탈퇴가 완료되었습니다.')
        return redirect('groups:list')
    
    context = {
        'group': group
    }
    return render(request, 'groups/group_leave.html', context)


# def email_view(request):
#     if request.method == 'GET':
#         form = ContactForm()
#     else:
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data['subject']
#             from_email = form.cleaned_data['from_email']
#             message = form.cleaned_data['message']
#             try:
#                 send_mail(subject, message, from_email, ['jaychoi1619@gmail.com'])
#             except BadHeaderError:
#                 return HttpResponse('Invalid header found.')
#             return redirect('pages:home')
#     return render(request, "groups/email_form.html", {'form': form})

groups/templates/groups/_card.html
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card card--group">
    <div class="img-wrapper">
      <img class="card-img-top" src="{{ group.photo.url }}" alt="" />
      <div class="card-img-overlay">
        <span
          class="card__badge card__badge--level badge badge-secondary text-white"
          >{{ group.level }}</span
        >
        <span
          class="card__badge card__badge--location badge badge-secondary text-white"
          ><i class="fas fa-map-marker"></i> {{ group.location }}</span
        >
      </div>
    </div>
    <div class="card-body text-center">
      <div class="group-heading text-center">
        <h4 class="group-heading__title">{{ group.name }}</h4>
        <div class="mb-2">
          <i class="far fa-calendar-alt text-secondary"></i> 시작일:
          {{ group.start_date }}
        </div>
      </div>
      <hr class="my-0" />
      <div class="row py-2">
        <div class="col-6">
          <i class="fas fa-graduation-cap text-secondary"></i> 기간:
          {{ group.duration }}주
        </div>
        <div class="col-6">
          <i class="fas fa-money-check text-secondary"></i> 
          {% if group.price != 0 %}
          {{ group.price }}만원
          {% else %}무료
          {% endif %}
        </div>
      </div>
      <hr class="my-0" />
      <div class="row pt-2">
        <div class="col-12">
          <i class="fas fa-clock text-secondary"></i> {{ group.day }},
          {{ group.time }}
        </div>
      </div>
      <div class="row pt-2 ">
        <div class="col-12">
          <i class="fas fa-user text-secondary"></i>
          {{ group.members.all.count }} / {{ group.size }}
        </div>
      </div>
      <hr class="my-2" />

      {% if group.status == 'open' %}
      <a href="{{ group.get_absolute_url }}" class="btn btn-secondary btn-block"
        >자세히</a
      >
      {% elif group.status == 'full' %}
      <a
        href="{{ group.get_absolute_url }}"
        class="btn btn-danger btn-block disabled"
        >정원 초과</a
      >
      {% else %}
      <a
        href="{{ group.get_absolute_url }}"
        class="btn btn-dark btn-block disabled"
        >모집 마감</a
      >
      {% endif %}
    </div>
  </div>
</div>

groups/templates/groups/group_create.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 내 스터디 만들기
{% endblock %}

{% block content %}

<section id="study-create" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-9 mx-auto">
        <div class="card">
          <div class="card-header bg-secondary text-white">
            <h4><i class="fas fa-user-plus"></i> 내 스터디 만들기</h4>
          </div>
          <div class="card-body">
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

groups/templates/groups/group_delete.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 내 스터디 삭제하기
{% endblock %}

{% block content %}

<section class="bg-light py-5 section section--delete">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-9 mx-auto">
        <div class="card">
          <div class="card-header bg-secondary text-white">
            <h4><i class="fas fa-user-plus"></i> 내 스터디 삭제하기</h4>
          </div>
          <div class="card-body">
							<form method="post">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-outline-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | {{ group.name }}
{% endblock %}

{% block content %}
<section id="detail" class="showcase">
  <div class="container py-4">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-5">{{ group.name }}</h1>
        <p class="lead">
					<i class="fas fa-map-marker"></i> <span class="mr-3">{{ group.location }}</span>
					<i class="fas fa-balance-scale"></i> <span class="mr-3">{{ group.level }}</span>
					<i class="fas fa-calendar-check"></i> <span class="">{{ group.day }}</span>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:home' %}">홈</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'groups:list' %}">스터디 찾기</a>
        </li>
        <li class="breadcrumb-item active">...</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listing -->
<section id="listing" class="py-4">
  <div class="container">
		<div class="row">
			<div class="col-md-8">
        {% if group.leader == request.user %}
          <!-- <div class="float-left">
            <div class="form-group">
              <span class="switch">
                <input type="checkbox" class="switch" id="switch-normal">
                <label for="switch-normal">Normal switch</label>
              </span>
            </div>
          </div> -->
					<div class="btn-group float-right">
						<a href="{% url 'groups:update' pk=group.pk %}" class="float-right btn btn-success mb-4">수정하기</a>	
						<a href="{% url 'groups:delete' pk=group.pk %}" class="float-right btn btn-danger mb-4">삭제하기</a>	
					</div>
				{% else %}
					{% if request.user.is_member %}
            {% if request.user not in group.members.all %}
              {% if group.members.count < group.size %}
              <a href="{% url 'groups:join' pk=group.pk %}" class="float-right btn btn-success mb-4">참여하기</a>
              {% else %}
              <a href="#" class="float-right btn btn-warning mb-4 disabled">정원 초과</a>
              {% endif %}
						{% else %}
							<a href="{% url 'groups:leave' pk=group.pk %}" class="float-right btn btn-danger mb-4">떠나기</a>										
						{% endif %}					
					{% endif %}		
				{% endif %}
			</div>
		</div>
		<div class="row">
      <!-- Group detail section -->
			<div class="col-md-8">
        <!-- Main Image -->
        <img src="{{ group.photo.url }}" alt="" class="img-main img-fluid mb-3">
       
        <!-- Fields -->
        <div class="row mb-5 fields">
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
							<li class="list-group-item text-secondary">
								<i class="fas fa-map-marker"></i> 지역:
								<span class="float-right">{{ group.location }}
								</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-calendar-check"></i> 요일:
								<span class="float-right">{{ group.day }}
								</span>
							</li>
              <li class="list-group-item text-secondary">
                <i class="fas fa-graduation-cap"></i> 기간:
                <span class="float-right">{{ group.duration }}주</span>
              </li>              
              <li class="list-group-item text-secondary">
                <i class="fas fa-user"></i> 정원:
                <span class="float-right">{{ group.members.count }} / {{ group.size }}명</span>
              </li>
            </ul>
          </div>
          <div class="col-md-6" id="detail-second">
            <ul class="list-group list-group-flush">
							<li class="list-group-item text-secondary">
								<i class="fas fa-calendar-alt"></i> 시작일:
								<span class="float-right">{{ group.start_date }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-clock"></i> 시간:
								<span class="float-right">{{ group.time }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-money-check"></i> 참여비:								
								{% if group.price == 0 %}
									<span class="float-right">무료</span>
								{% else %}
										<span class="float-right">{{ group.price }}만원</span>
								{% endif %}									
							</li>
              <li class="list-group-item text-secondary">
									<i class="fas fa-balance-scale"></i> 레벨:
                <span class="float-right">{{ group.level }}</span>
              </li>
            </ul>
          </div>
        </div>

        <!-- Description -->
        <div class="row mb-5" id="study-intro">
          <div class="col-md-12">
						<h4>스터디 소개</h4>
						<hr>
						<p>{{ group.description|linebreaks }}</p>
          </div>
        </div>

          
      </div>



      <!-- Leader profile section -->
      <div class="col-md-4">
        <div class="card mb-3">
					<div class="card-header h5 bg-secondary text-white">리더 프로필</div>
          <img class="card-img-top" src="{{ group.leader.profile.photo.url }}" alt="">
          <div class="card-body">
						<h4 class="text-secondary">{{ group.leader.name }}</h6>
						<p class="card-text"><span class="fas fa-star"></span> {{ group.leader.profile.get_average_rating }}</p>
						<p class="card-text">{{ group.leader.profile.bio|linebreaks }}</p>
          </div>
        </div>
        <!-- <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">질문하기</button> -->
      </div>


    </div>

     <!-- Comment -->
    <div class="row my-5" id="leader-review">
      <div class="col-md-8">
        <h4>리더 리뷰</h4>
        <hr>
        {% if request.user in group.members.all %}
          <form method="POST" action="{% url 'comments:create' %}">{% csrf_token %}
            {{ form|crispy }}
            <input type="hidden" name="next" value="{{ request.path }}">
            <input type="hidden" name="leader_id" value="{{ group.leader.id }}">
            <button class="btn btn-block btn-secondary mb-3">리뷰 쓰기</button>
          </form>
        {% endif %}
        {% for comment in comments %}
          {% include 'comments/_comment.html' with comment=comment checked=comment.get_star_checked unchecked=comment.get_star_unchecked %}
        {% endfor %}
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</section>

{% endblock %}

groups/templates/groups/group_join.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 그룹 참여하기
{% endblock %}

{% block content %}

<section id="login" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4><i class="fas fa-sign-in-alt"></i> 스터디 참여하기</h4>
          </div>
          <div class="card-body">
            <div class="card bg-light mb-3">
              <div class="card-header"><strong>{{ group.location }}</strong>에서 진행되는 <strong>{{ group.leader.name }}</strong>님의 <strong>{{ group.level }}</strong> 영어회화 스터디!</div>
              <img src="{{ group.photo.url }}" alt="" class="card-img-top">
              <div class="card-body">
                <h5 class="card-title">{{ group.name }}</h5>
                <p class="card-text">
                  시작일: {{ group.start_date }} <br>
                  주기: 매주 {{ group.day }} <br>
                  기간: {{ group.duration }}주 <br>
                  참여비: {% if group.price == 0 %}무료{% else %}{{ group.price }}만원{% endif %}
                </p>
              </div>
              <div class="card-footer">참여를 확정하시면, 입력해주신 연락처로 리더님이 직접 스터디 안내를 드립니다.</div>
            </div>
						<form method="post">
							{% csrf_token %}
							<div class="form-group">
								<label for="contact" class="col-form-label requiredField">연락처*</label>
								<input type="text" name="contact" id="contact-input" class="form-control" placeholder="전화번호나 카톡ID 등 연락가능한 연락처를 입력해주세요" required>
							</div>
							<button type="submit" class="btn btn-secondary btn-block">학인</button>
						</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

groups/templates/groups/group_leave.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}
  | 스터디 떠나기
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4><i class="fas fa-user-plus"></i> 스터디 떠나기</h4>
          </div>
          <div class="card-body">
						<h5 class="card-title"><{{ group.name }}> 스터디를 떠나시겠어요?</h5>
						<form method="post">
							{% csrf_token %}
							<input type="submit" value="학인" class="btn btn-secondary btn-block">
						</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

groups/templates/groups/group_list.html
{% extends 'base.html' %}

{% block title %}
  | 나에게 맞는 영어회화 스터디 찾기
{% endblock %}

{% block content %}

<!-- Showcase -->
<section id="list" class="showcase">
  <div class="container">
    <div class="row text-center">
      <div class="col">
        <h1 class="display-5 mb-4">나에게 맞는 스터디를 찾아보세요!</h1>
				{% include 'partials/_search_form.html' %}
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
{% include 'partials/_breadcrumb.html' with current="스터디 찾기" %}

<!-- Listings -->
<section id="groups" class="py-4">
  <div class="container">
    <!-- Search Queries -->
    {% if queries %}
    <div class="row">
      <div class="col mb-4 text-center">
      {% for query in queries %}
        {% if query != '' %}
         <span class="h4">'{{ query }}'</span>  
        {% endif %}
      {% endfor %}<span class="h5">에 대한 검색결과</span>
      <hr>
      </div>
    </div>
    {% endif %}
		<div class="row">        
			{% if group_list %}
			{% for group in group_list %}
				{% include 'groups/_card.html' with group=group %}
			{% endfor %}
			{% else %}
			<div class="col-md-12">
				<p>No groups available</p>
			</div>
			{% endif %}
		</div>
		<!-- Pagination -->
    {% include 'partials/_paginator.html' %}
  </div>
</section>

{% endblock %}

groups/templates/groups/group_update.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 내 스터디 업데이트
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-secondary text-white">
            <h4><i class="fas fa-user-plus"></i> 내 스터디 수정하기</h4>
          </div>
          <div class="card-body">
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}