accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    LeaderGroupListView, 
    MemberGroupListView,
    LeaderSignupView,
    MemberSignupView,
    SignupView,
    CustomLoginView,
    ProfileView,
    ProfileUpdateView,
)

app_name = 'accounts'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('signup/leader/', LeaderSignupView.as_view(), name='leader_signup'),
    path('signup/member', MemberSignupView.as_view(), name='member_signup'),
    path('my_group/leader/', LeaderGroupListView.as_view(), name='leader_group'),
    path('my_group/member/', MemberGroupListView.as_view(), name='member_group'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
]

pages/urls.py
from django.urls import path

from .views import HomeView, AboutView

app_name = 'pages'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    is_member = models.BooleanField(_('멤버'), default=False)
    is_leader = models.BooleanField(_('리더'), default=False)
    email = models.EmailField(_('이메일'), unique=False) # set to true later
    name = models.CharField(_('이름'), max_length=30)
    contact = models.CharField(_('연락처'), null=True, blank=True, max_length=120)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(_('자기소개'))
    photo = models.ImageField(_('프로필 사진'), upload_to='accounts/%Y/%m/%d/',
                                        default='default/profile-default.jpg')

    def __str__(self):
        return self.user.username

    def get_average_rating(self):
        comment_qs = self.user.comment_to.all()
        total_rating = 0
        for comment in comment_qs:
            total_rating += comment.rating
        if comment_qs.count():
            average_rating = total_rating / comment_qs.count()
        else:
            average_rating = 0
        return round(average_rating, 2)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    profile, created = Profile.objects.get_or_create(user=instance)
    print(created)
    profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

from .models import Profile

User = get_user_model()

class SignupForm(UserCreationForm):
    username = forms.CharField(label='ID')
    email = forms.EmailField(label='이메일', max_length=254)
    name = forms.CharField(label='성명', max_length=30)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'password1', 'password2']

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     username = self.cleaned_data.get('username')
    #     if email and User.objects.filter(email=email).exclude(username=username).exists():
    #         raise forms.ValidationError('해당 이메일로 가입된 회원이 이미 있습니다')
    #     return email

    # def save(self, commit=True):
    #     user = super().save(commit=False)
    #     user.is_member = True
    #     if commit:
    #         user.save()
    #     return user


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(label='ID')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'photo']

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, FormView, View

from groups.models import Group
from .models import Profile
from .forms import SignupForm, CustomLoginForm, ProfileForm

User = get_user_model()


class LeaderGroupListView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/leader_group_list.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if not request.user.is_leader:
            return redirect('pages:home')
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.filter(leader=self.request.user)
        return context


class MemberGroupListView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/member_group_list.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if not request.user.is_member:
            return redirect('pages:home')
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.filter(members=self.request.user)
        return context


class SignupView(TemplateView):
    template_name = 'accounts/signup.html'


class CustomLoginView(LoginView):
    template_name = 'registration/login.html'
    authentication_form = CustomLoginForm


class LeaderSignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/leader_signup.html'

    def form_valid(self, form):
        user = form.save()  # creates a user instance by using the input of the form
        user.is_leader = True
        user.save()
        login(self.request, user)
        return redirect('pages:home')


class MemberSignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/member_signup.html'

    def form_valid(self, form):
        user = form.save()  # creates a user instance by using the input of the form
        user.is_member = True
        user.save()
        login(self.request, user)
        return redirect('pages:home')


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_object_or_404(Profile, user=self.request.user)
        return context


# def profile_update_view(request):
#     profile = get_object_or_404(Profile, user=request.user)
#     if request.method == 'POST':
#         form = ProfileForm(request.POST, request.FILES, instance=profile)
#         if form.is_valid():
#             form.save()
#             return redirect('accounts:profile')
#     else:
#         form = ProfileForm(instance=profile)
#     context = {
#         'form': form
#     }
#     return render(request, 'accounts/profile_update.html', context)


class ProfileUpdateView(LoginRequiredMixin, View):
    form_class = ProfileForm
    template_name = 'accounts/profile_update.html'

    def get(self, request, *args, **kwargs):
        profile = get_object_or_404(Profile, user=request.user)
        form = self.form_class(instance=profile)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        profile = get_object_or_404(Profile, user=request.user)
        form = self.form_class(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
        return render(request, self.template_name, {'form': form})


# Using signals to show messages
def show_logout_message(sender, user, request, **kwargs):
    messages.info(request, '로그아웃 되었습니다.')

user_logged_out.connect(show_logout_message)


def show_login_message(sender, user, request, **kwargs):
    messages.success(request, '{}님 환영합니다.'.format(user.name))

user_logged_in.connect(show_login_message)

accounts/templates/accounts/leader_group_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  | 내 스터디 목록
{% endblock %}

{% block content %}
<!-- Showcase -->
<section id="mygroup" class="showcase">
  <div class="container py-5">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-5">내 스터디</h1>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
{% include 'partials/_breadcrumb.html' with current="내 스터디" %}

<section id="about" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-9 mx-auto">
        <h4>리드 중인 스터디</h4>
        <hr>
        {% if groups %}
          <div class="row">
            
            {% for group in groups %}
            <div class="col-md-6">
              <div class="card border-secondary mb-3">
                <div class="card-header text-center h4"><a href="{{ group.get_absolute_url }}">{{ group.name }}</a></div>
                <div class="card-body text-secondary">
                  {% if group.members.all %}
                  <p>{{ group.members.count }}명의 멤버가 참여 중입니다.</p>
                  {% for member in group.members.all %}
                  <ul class="list-group mb-2">
                    <li class="list-group-item list-group-item-secondary"><i class="far fa-user mr-2"></i>{{ member.name }}</li>
                    <li class="list-group-item"><i class="fas fa-mobile-alt mr-2"></i>{{ member.contact }}</li>
                  </ul>
                  {% endfor %}
                  {% else %}
                  <p>참여 중인 멤버가 없습니다.</p>
                  {% endif %}
                </div>
              </div>
            </div>
            {% endfor %}
              
          </div>
        {% else %}
          <p>현재 리드 중인 스터디 그룹이 없습니다.</p>
        {% endif %}
    </div>
  </div>
</section>

{% endblock %}

accounts/templates/accounts/leader_signup.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 리더로 가입하기
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-9 mx-auto">
        <div class="card">
          <div class="card-header bg-secondary text-white">
            <h4><i class="fas fa-user-plus"></i> 리더로 가입하기</h4>
          </div>
          <div class="card-body">
							<form method="post">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}
	

accounts/templates/accounts/member_group_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  | 내 스터디 목록
{% endblock %}

{% block content %}
<!-- Showcase -->
<section id="mygroup" class="showcase">
  <div class="container py-5">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-5">My Study</h1>
      </div>
    </div>
  </div>
</section>


<!-- Breadcrumb -->
{% include 'partials/_breadcrumb.html' with current="내 스터디" %}

<section id="about" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-9 mx-auto">
        <h4>참여 중인 스터디</h4>
        <hr>
        {% if groups %}
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">스터디</th>
              <th scope="col" class="table-hide">리더</th>
              <th scope="col" class="table-hide">시작일</th>
            </tr>
          </thead>
          <tbody>
            {% for group in groups %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td><a href="{{ group.get_absolute_url }}">{{ group.name }}</a></td>
              <td class="table-hide">{{ group.leader.name }}</td>
              <td class="table-hide">{{ group.start_date }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
          <p>현재 참여 중인 스터디가 없습니다.</p>
        {% endif %}
    </div>
  </div>
</section>

{% endblock %}

accounts/templates/accounts/member_signup.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 멤버로 가입하기
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-9 mx-auto">
        <div class="card">
          <div class="card-header bg-secondary text-white">
            <h4><i class="fas fa-user-plus"></i> 멤버로 가입하기</h4>
          </div>
          <div class="card-body">
							<form method="post">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}
	

accounts/templates/accounts/profile.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 내 프로필
{% endblock %}

{% block content %}
<!-- Showcase -->
<section id="profile" class="showcase">
  <div class="container py-5">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-5">Profile</h1>
      </div>
    </div>
  </div>
</section>


<section id="myprofile" class="bg-light pt-2 pb-4">
  <!-- Breadcrumb -->
  {% include 'partials/_breadcrumb.html' with current="프로필" %}
  <div class="container mt-3">
    <div class="row">
      <div class="col-lg-9 col-md-12 mx-auto">
        <div class="card">
          <div class="card-header bg-secondary text-white">
            <h4><i class="fas fa-sign-in-alt"></i> 나의 프로필</h4>
          </div>
          <div class="card-body pb-0">
            <div class="row">
              <div class="col-md-6 col-lg-4 p-3 text-center">
                <img src="{{ profile.photo.url }}" alt="" class="img-fluid rounded-circle">
                <h4 class="mt-3">{{ profile.user.name }}</h4>
              </div>
              <div class="col-md-6 col-lg-8 p-3">
                <h5>자기소개</h5>
                <hr>
                <p>{{ profile.bio|linebreaks }}</p>
              </div>
            </div>
          </div>
          <div class="card-footer">
            <a href="{% url 'accounts:profile_update' %}" class="btn btn-secondary btn-block">수정하기</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

accounts/templates/accounts/profile_teacher.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  | 프로필
{% endblock %}

{% block content %}

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:home' %}">
            <i class="fas fa-home"></i> 홈</a>
        </li>
        <li class="breadcrumb-item active"> 프로필</li>
      </ol>
    </nav>
  </div>
</section>

<section id="about" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-9 mx-auto">
        <h2>내 스터디 그룹</h2>
        <hr>
        
        {% if groups %}
        <div class="accordion" id="accordionExample">
        {% for group in groups %}
              <div class="card mb-3">
                <div class="card-header" id="heading{{ forloop.counter }}">
                  <h5 class="mb-0">
                    <a href="{{ group.get_absolute_url }}">#{{ forloop.counter }}. {{ group.name }}</a>
                    <button class="btn btn-secondary float-right py-0" type="button" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                      멤버 리스트
                    </button>
                  </h5>
                </div>
            
                <div id="collapse{{ forloop.counter }}" class="collapse" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordionExample">
                  <div class="card-body">
                      {% if group.members.all %}
                        <table class="table table-striped table-light">
                          <thead>
                            <tr>
                              <th scope="col">멤버</th>
                              <th scope="col">이름</th>
                              <th scope="col">연락처</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for member in group.members.all %}
                              <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ member.name }}</td>
                                {% if member.contact %}
                                  <td>{{ member.contact }}</td>
                                {% else %}
                                  <td>{{member.email}}</td>
                                {% endif %}
                              </tr>
                            {% endfor %}
                          </tbody>
                        </table>                      
                      {% else %}
                        <p>현재 참여 중인 멤버가 없습니다.</p>
                      {% endif %}
                        
                  </div>
                </div>
              </div>
              
              {% endfor %}
            </div>
        {% else %}
          <p>현재 리드 중인 스터디 그룹이 없습니다.</p>
        {% endif %}
    </div>
  </div>
</section>

{% endblock %}


{% comment %}
<section id="group-list">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h1>My Groups</h1>
          <ul>
            {% for group in groups %}
            <li>
              <h4>
                <a href="{{ group.get_absolute_url }}">{{ group.name }}</a>
              </h4>
              {% for member in group.members.all %}
              <p>{{ member.username }}: {{ member.email }}</p>
              {% endfor %}
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </section>
  
{% endcomment %}
  

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 프로필 업데이트
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4><i class="fas fa-user-plus"></i> 프로필 수정하기</h4>
          </div>
          <div class="card-body">
							<form method="post" enctype="multipart/form-data">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}
  | 회원가입
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-9 mx-auto">
        <div class="card card--register">
          <div class="card-header bg-secondary text-white">
            <h4><i class="fas fa-user-plus"></i> 회원가입</h4>
          </div>
          <div class="card-body">
							<a href="{% url 'accounts:leader_signup' %}" class="btn btn-outline-secondary btn-block">리더로 가입하기</a>
							<a href="{% url 'accounts:member_signup' %}" class="btn btn-secondary btn-block">멤버로 가입하기</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

accounts/templates/accounts/signup_student.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 멤버로 가입하기
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4><i class="fas fa-user-plus"></i> 멤버로 가입하기</h4>
          </div>
          <div class="card-body">
							<form method="post">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}
	

accounts/templates/accounts/signup_teacher.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  | 리더로 가입하기
{% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4><i class="fas fa-user-plus"></i> 리더로 가입하기</h4>
          </div>
          <div class="card-body">
							<form method="post">
								{% csrf_token %}
								{{ form|crispy }}
								<button type="submit" class="btn btn-secondary btn-block">확인</button>
							</form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}
	